language: node_js
node_js:
  - "10.14"
before_install:
  - npm install -g yarn
script: skip
branches:
  only:
    - main

before_deploy:
  - rm -rf node_modules
  - zip -r sench-devenv *
  - mkdir -p deploy
  - mv sench-devenv.zip deploy/sench-devenv.zip

deploy:
  - provider: S3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: senchcicd
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: yuJaeWoo/sench-devenv
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: senchcicd
    key: sench-devenv.zip
    bundle_type: zip
    application: cdservice
    deployment_group: cicddeploygroup
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: yuJaeWoo/sench-devenv
      branch: main


